version: '3'
services:
  todotests:
    build: ./todo-app/tests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    networks:
      - todo-app
  todofrontend:
    build: ./todo-app/front-end
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - todo-app
  todobackend:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    networks:
      - todo-app

networks:
  todo-app:

      