version: '3'
services:
  todotests:
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
  todofrontend:
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
  todobackend:
    ports:
      - 3001:3001
      